---
- vars:
      env: prod
  vars_files: 
     - ["aws_vars/{{env}}/main.yml"]
     - ["aws_vars/{{env}}/vpc_info.yml"]
  hosts: local
  connection: local
  gather_facts: False
  tags: EC2_APP instance provisioning
  roles:
    - role: ec2_app
