---
- vars:
      env: prod
  vars_files: 
     - ["aws_vars/{{env}}/main.yml"]
     - ["aws_vars/{{env}}/vpc_info.yml"]
  hosts: local
  connection: local
  gather_facts: True
  tags: ELB provisioning - register EC2 instances
  roles:
    - role: elb
